### ISSUE TITLE
How would I use hashtags?

### ISSUE THREAD

**Issue by ankon** [Collaborne/widget-sample#3]

**Comment by ankon** [comment]
Basic idea: Our integration API can accept labels in an array, so the widget itself should provide that content. One option is to build a "parser" for hashtags on the frontend, but that can lead to complex problems. We propose to actually build a label-input control instead, where one can select from pre-defined tags.

**Comment by ronnyroeller** [comment]
> We propose to actually build a label-input control instead, where one can select from pre-defined tags.

The sample code shows now how to post captured labels: https://github.com/Collaborne/widget-sample/blob/435b9d3855b008f5981acd4a8f245266d030c6a9/src/next-client.js#L27
